---
### CHANGED ###

popup_button_power:
  template:
    - "popup_button"
    - "ulm_language_variables"
  icon: "mdi:power"
  name: "[[[ return variables.ulm_popups_power ]]]"
  styles:
    name:
      - text-transform: "uppercase"
      - color: "rgba(var(--color-theme),0.5)"
    icon:
      - color: "var(--card-background-color)"
    img_cell:
      - background-color: "var(--primary-color)"
      - box-shadow: "0px 2px 4px 0px rgba(0,0,0,0.16)"
  tap_action:
    action: "toggle"
